export type Lang = "en" | "th";

export const copy = {
  en: {
    eyebrow: "HRI Wellness Living Lab",
    title: "HRI Passport: greet once, every robot knows you",
    subtitle: "Meet the atlas robot. It waits for your wai, approaches only as close as you are comfortable, and remembers how you like robots to behave. Your preferences become a passport any robot in the atlas can read.",
    haveCode: "I already have a passport",
    robotLabel: "Living Lab robot",
    cameraPreview: "Camera preview (on-device only)",
    introSpeech: "Hello. When you are ready, press Start. I will follow your lead.",
    statusIdle: "Ready",
    introTitle: "How it works (about 1 minute)",
    introSteps: [
      "Greet the robot with a wai. It waits for you first.",
      "It steps closer one step at a time. Tell it when it is too close, too fast, or just right.",
      "Choose how it looks at you and whether it speaks.",
      "Get your HRI Passport (a code and QR) and meet another robot with it."
    ],
    privacy: "Camera is optional and runs on this device only. No video is stored or sent. Only your preferences and the interaction log are saved.",
    start: "Start",
    loadingRobot: "Loading robot…",
    cameraOn: "Use camera (optional)",
    cameraOff: "Turn camera off",
    cameraLoading: "Starting camera…",
    cameraError: "Camera unavailable, buttons still work",
    personSeen: "person seen",
    noPerson: "no person",
    waitSpeech: "…",
    statusWaitButton: "Waiting for your greeting",
    statusWaitCamera: "Waiting for your wai (camera)",
    waiDetecting: "Wai detected, hold it…",
    greetTitle: "Greet the robot",
    greetHelp: "The robot is waiting quietly. Make a wai (hands together at your chest). With the camera on it will see you; otherwise press the button.",
    waiButton: "I made a wai",
    waiSpeech: "สวัสดีครับ. Thank you for greeting me.",
    statusWaiReturned: "Robot returned your wai",
    askApproach: "May I come a little closer? Tell me how this feels.",
    statusApproach: (n: number, total: number) => `Approach step ${n} of ${total}`,
    announceStep: "I am going to step a little closer…",
    closestAsk: "This is as close as I come. Is this comfortable?",
    approachTitle: "How close is comfortable?",
    approachHelp: "The robot announces each step before it moves.",
    leanHint: "Leaning back also tells it you are uncomfortable.",
    distanceLabel: "Robot distance",
    continue: "Continue",
    comfortable: "Comfortable here",
    tooClose: "Too close",
    tooFast: "Too fast",
    sorry: "Sorry. I will step back and stay here.",
    sorryLean: "I saw you lean back. Sorry, I will step back.",
    slower: "Okay. I will move more slowly.",
    askGaze: "When I talk with you, is it okay if I look at you like this?",
    statusGaze: "Choosing eye contact",
    gazeTitle: "Eye contact",
    gazeDirectBtn: "Yes, look at me",
    gazeSoftBtn: "Please look away a little",
    gazeDirect: "Good. I will look at you when we talk.",
    gazeSoft: "Like this? I will keep my eyes a little lower.",
    askVoice: "Last question: should I speak out loud, or show text only?",
    statusVoice: "Choosing voice",
    voiceTitle: "Voice",
    voiceYes: "Speak out loud",
    voiceNo: "Text only",
    voiceOn: "I will speak out loud. Thank you.",
    voiceOff: "I will show text only. Thank you.",
    statusSaving: "Saving your passport…",
    statusDone: "Passport ready",
    doneSpeech: (code: string) => `Your HRI Passport is ${code}. Any robot in the atlas can now meet you the way you like.`,
    passportTitle: "Your HRI Passport",
    qrAlt: "QR code for your HRI Passport",
    codeLabel: "Passport code",
    factGreeting: "Greeting", wai: "wai",
    factDistance: "Comfortable distance",
    factSpeed: "Movement", slow: "slower", normal: "normal",
    factGaze: "Eye contact", soft: "soft (looks away a little)", direct: "direct",
    factVoice: "Voice", on: "on", off: "text only",
    scanHint: "Scan the QR on another screen or phone: a different robot will greet you with your preferences.",
    meetNow: "Meet another robot with this passport",
    again: "Start again",
    logTitle: "Interaction log",
    findingsTitle: "Living Lab findings (live)",
    findingsSub: "Aggregated from every encounter saved in this atlas. No personal data: only interaction preferences.",
    statPassports: "passports created",
    statMeetings: "passport meetings",
    statDistance: "typical comfortable distance",
    statSoftGaze: "prefer softer eye contact",
    statSlowed: "asked the robot to slow down",
    statTooClose: "\"too close\" signals",
    dbOffline: "Live data is unavailable right now. Nothing is substituted.",
    robotsTitle: "Care robots in the atlas that can read a passport",
    robotsSub: "From the robot registry. Choose one to meet with your passport.",
    meetThisRobot: "Meet with my passport →"
  },
  th: {
    eyebrow: "HRI Wellness Living Lab",
    title: "HRI Passport: ไหว้ครั้งเดียว หุ่นยนต์ทุกตัวรู้จักคุณ",
    subtitle: "พบหุ่นยนต์ของ Atlas หุ่นจะรอให้คุณไหว้ก่อน เข้าใกล้เท่าที่คุณสบายใจ และจำว่าคุณชอบให้หุ่นยนต์ทำตัวอย่างไร ความชอบของคุณจะกลายเป็นพาสปอร์ตที่หุ่นยนต์ทุกตัวใน Atlas อ่านได้",
    haveCode: "ฉันมีพาสปอร์ตแล้ว",
    robotLabel: "หุ่นยนต์ Living Lab",
    cameraPreview: "ภาพจากกล้อง (ประมวลผลในเครื่องเท่านั้น)",
    introSpeech: "สวัสดีครับ พร้อมเมื่อไหร่กด เริ่ม ได้เลย ผมจะทำตามจังหวะของคุณ",
    statusIdle: "พร้อม",
    introTitle: "ขั้นตอน (ประมาณ 1 นาที)",
    introSteps: [
      "ไหว้ทักทายหุ่นยนต์ หุ่นจะรอให้คุณทักก่อน",
      "หุ่นจะขยับเข้าใกล้ทีละก้าว บอกได้ว่าใกล้ไป เร็วไป หรือกำลังดี",
      "เลือกว่าอยากให้หุ่นสบตาแบบไหน และพูดออกเสียงหรือไม่",
      "รับ HRI Passport (รหัสและ QR) แล้วไปพบหุ่นตัวอื่นได้เลย"
    ],
    privacy: "กล้องเป็นตัวเลือก ประมวลผลในเครื่องนี้เท่านั้น ไม่บันทึกหรือส่งภาพ ระบบเก็บเฉพาะความชอบของคุณและบันทึกการโต้ตอบ",
    start: "เริ่ม",
    loadingRobot: "กำลังโหลดหุ่นยนต์…",
    cameraOn: "ใช้กล้อง (ไม่บังคับ)",
    cameraOff: "ปิดกล้อง",
    cameraLoading: "กำลังเปิดกล้อง…",
    cameraError: "ใช้กล้องไม่ได้ ใช้ปุ่มแทนได้",
    personSeen: "เห็นคน",
    noPerson: "ไม่เห็นคน",
    waitSpeech: "…",
    statusWaitButton: "รอคุณทักทาย",
    statusWaitCamera: "รอคุณไหว้ (กล้อง)",
    waiDetecting: "เห็นการไหว้แล้ว ค้างไว้สักครู่…",
    greetTitle: "ทักทายหุ่นยนต์",
    greetHelp: "หุ่นยนต์กำลังรออย่างสงบ ลองไหว้ (พนมมือระดับอก) ถ้าเปิดกล้องหุ่นจะเห็นเอง ถ้าไม่เปิดให้กดปุ่ม",
    waiButton: "ฉันไหว้แล้ว",
    waiSpeech: "สวัสดีครับ ขอบคุณที่ทักทายผมครับ",
    statusWaiReturned: "หุ่นยนต์ไหว้ตอบแล้ว",
    askApproach: "ผมขอเข้าไปใกล้อีกนิดได้ไหมครับ บอกผมได้เลยว่ารู้สึกอย่างไร",
    statusApproach: (n: number, total: number) => `ก้าวที่ ${n} จาก ${total}`,
    announceStep: "ผมกำลังจะขยับเข้าไปใกล้อีกนิดนะครับ…",
    closestAsk: "ผมจะเข้าใกล้ได้มากสุดแค่นี้ ระยะนี้สบายใจไหมครับ",
    approachTitle: "ระยะไหนสบายใจ?",
    approachHelp: "หุ่นยนต์จะบอกก่อนทุกครั้งที่ขยับ",
    leanHint: "ถ้าเอนตัวหนี หุ่นจะรู้ว่าคุณไม่สบายใจ",
    distanceLabel: "ระยะของหุ่นยนต์",
    continue: "เข้ามาได้",
    comfortable: "ระยะนี้กำลังดี",
    tooClose: "ใกล้ไป",
    tooFast: "เร็วไป",
    sorry: "ขอโทษครับ ผมจะถอยออกมาและอยู่ตรงนี้",
    sorryLean: "ผมเห็นคุณเอนตัวหนี ขอโทษครับ ผมจะถอยออกมา",
    slower: "ได้ครับ ผมจะขยับช้าลง",
    askGaze: "เวลาคุยกัน ผมมองหน้าคุณแบบนี้ได้ไหมครับ",
    statusGaze: "เลือกการสบตา",
    gazeTitle: "การสบตา",
    gazeDirectBtn: "มองได้เลย",
    gazeSoftBtn: "หลบสายตานิดหนึ่ง",
    gazeDirect: "ได้ครับ ผมจะมองคุณเวลาเราคุยกัน",
    gazeSoft: "แบบนี้ไหมครับ ผมจะมองต่ำลงหน่อย",
    askVoice: "ข้อสุดท้าย อยากให้ผมพูดออกเสียง หรือแสดงเป็นข้อความอย่างเดียวครับ",
    statusVoice: "เลือกเสียงพูด",
    voiceTitle: "เสียงพูด",
    voiceYes: "พูดออกเสียง",
    voiceNo: "ข้อความอย่างเดียว",
    voiceOn: "ผมจะพูดออกเสียงครับ ขอบคุณครับ",
    voiceOff: "ผมจะแสดงเป็นข้อความครับ ขอบคุณครับ",
    statusSaving: "กำลังบันทึกพาสปอร์ต…",
    statusDone: "พาสปอร์ตพร้อมแล้ว",
    doneSpeech: (code: string) => `HRI Passport ของคุณคือ ${code} ตอนนี้หุ่นยนต์ทุกตัวใน Atlas จะพบคุณในแบบที่คุณชอบครับ`,
    passportTitle: "HRI Passport ของคุณ",
    qrAlt: "QR code ของ HRI Passport",
    codeLabel: "รหัสพาสปอร์ต",
    factGreeting: "การทักทาย", wai: "ไหว้",
    factDistance: "ระยะที่สบายใจ",
    factSpeed: "ความเร็ว", slow: "ช้าลง", normal: "ปกติ",
    factGaze: "การสบตา", soft: "หลบสายตาเล็กน้อย", direct: "มองตรง",
    factVoice: "เสียงพูด", on: "เปิด", off: "ข้อความอย่างเดียว",
    scanHint: "สแกน QR บนจอหรือมือถืออีกเครื่อง หุ่นยนต์อีกตัวจะทักทายคุณตามความชอบนี้ทันที",
    meetNow: "ไปพบหุ่นยนต์ตัวอื่นด้วยพาสปอร์ตนี้",
    again: "เริ่มใหม่",
    logTitle: "บันทึกการโต้ตอบ",
    findingsTitle: "ผลจาก Living Lab (ข้อมูลจริง)",
    findingsSub: "รวมจากทุกการพบที่บันทึกใน Atlas ไม่มีข้อมูลส่วนบุคคล มีเฉพาะความชอบในการโต้ตอบ",
    statPassports: "พาสปอร์ตที่สร้าง",
    statMeetings: "การพบด้วยพาสปอร์ต",
    statDistance: "ระยะที่สบายใจโดยทั่วไป",
    statSoftGaze: "ชอบให้หลบสายตาเล็กน้อย",
    statSlowed: "ขอให้หุ่นขยับช้าลง",
    statTooClose: "ครั้งที่บอกว่า \"ใกล้ไป\"",
    dbOffline: "ขณะนี้ดึงข้อมูลจริงไม่ได้ ระบบไม่แสดงข้อมูลทดแทน",
    robotsTitle: "หุ่นยนต์ดูแลใน Atlas ที่อ่านพาสปอร์ตได้",
    robotsSub: "จาก robot registry เลือกหุ่นที่ต้องการพบด้วยพาสปอร์ตของคุณ",
    meetThisRobot: "พบด้วยพาสปอร์ตของฉัน →"
  }
} as const;
